[workspace]
members = ["loxlang", "loxint", "loxwasm"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
nom = "8"
thiserror = "2"
miette = "7"
chumsky = "1.0.0-alpha.7"
