[workspace]
members = ["loxlang", "loxint", "loxwasm"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
nom = "8"
thiserror = "2"
miette = "7"
chumsky = { version = "0.12", features = ["lexical-numbers"] }
regex = "1"
